version: "3"
services:
  user_backend_postgres:
    image: postgres:13-alpine
    container_name: user_backend_postgres
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /var/lib/postgresql/data
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
    - "5432:5432"
  user_backend_pgadmin:
    image: dpage/pgadmin4:latest
    container_name: user_backend_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "8001:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on: 
        - user_backend_postgres
volumes:
  db_data:
  pgadmin_data: